//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ahorro
    {
        public int id { get; set; }
        public Nullable<int> cedula { get; set; }
        public Nullable<long> capital { get; set; }
        public Nullable<decimal> interes { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
