//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id { get; set; }
        public Nullable<int> cod_prestamo { get; set; }
        public Nullable<long> monto_pago { get; set; }
        public Nullable<int> modalida_pago { get; set; }
    
        public virtual prestamo prestamo { get; set; }
        public virtual tipo_pago tipo_pago { get; set; }
    }
}
