//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usuarioid { get; set; }
        public string usuario1 { get; set; }
        public string clave { get; set; }
        public Nullable<int> rol { get; set; }
    
        public virtual role role { get; set; }
    }
}
